# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.rotated_secret_update_splunk import RotatedSecretUpdateSplunk  # noqa: E501
from akeyless.rest import ApiException

class TestRotatedSecretUpdateSplunk(unittest.TestCase):
    """RotatedSecretUpdateSplunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RotatedSecretUpdateSplunk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.rotated_secret_update_splunk.RotatedSecretUpdateSplunk()  # noqa: E501
        if include_optional :
            return RotatedSecretUpdateSplunk(
                add_tag = [
                    '0'
                    ], 
                audience = '0', 
                authentication_credentials = 'use-user-creds', 
                auto_rotate = '0', 
                delete_protection = '0', 
                description = 'default_metadata', 
                expiration_date = '0', 
                hec_token = '0', 
                item_custom_fields = {
                    'key' : '0'
                    }, 
                json = True, 
                keep_prev_version = '0', 
                key = '0', 
                max_versions = '0', 
                name = '0', 
                new_name = '0', 
                password_length = '0', 
                rm_tag = [
                    '0'
                    ], 
                rotation_event_in = [
                    '0'
                    ], 
                rotation_hour = 56, 
                rotation_interval = '0', 
                splunk_token = '0', 
                token = '0', 
                token_owner = '0', 
                uid_token = '0'
            )
        else :
            return RotatedSecretUpdateSplunk(
                name = '0',
        )

    def testRotatedSecretUpdateSplunk(self):
        """Test RotatedSecretUpdateSplunk"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
