# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.account_custom_field_update import AccountCustomFieldUpdate  # noqa: E501
from akeyless.rest import ApiException

class TestAccountCustomFieldUpdate(unittest.TestCase):
    """AccountCustomFieldUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AccountCustomFieldUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.account_custom_field_update.AccountCustomFieldUpdate()  # noqa: E501
        if include_optional :
            return AccountCustomFieldUpdate(
                id = 56, 
                json = True, 
                name = '0', 
                required = True, 
                token = '0', 
                uid_token = '0'
            )
        else :
            return AccountCustomFieldUpdate(
                id = 56,
        )

    def testAccountCustomFieldUpdate(self):
        """Test AccountCustomFieldUpdate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
