# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.create_auth_method_o_auth2 import CreateAuthMethodOAuth2  # noqa: E501
from akeyless.rest import ApiException

class TestCreateAuthMethodOAuth2(unittest.TestCase):
    """CreateAuthMethodOAuth2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateAuthMethodOAuth2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.create_auth_method_o_auth2.CreateAuthMethodOAuth2()  # noqa: E501
        if include_optional :
            return CreateAuthMethodOAuth2(
                access_expires = 56, 
                audience = '0', 
                bound_client_ids = [
                    '0'
                    ], 
                bound_ips = [
                    '0'
                    ], 
                issuer = '0', 
                jwks_uri = '0', 
                name = '0', 
                token = '0', 
                uid_token = '0'
            )
        else :
            return CreateAuthMethodOAuth2(
                jwks_uri = '0',
                name = '0',
        )

    def testCreateAuthMethodOAuth2(self):
        """Test CreateAuthMethodOAuth2"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
