# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.update_auth_method_cert import UpdateAuthMethodCert  # noqa: E501
from akeyless.rest import ApiException

class TestUpdateAuthMethodCert(unittest.TestCase):
    """UpdateAuthMethodCert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateAuthMethodCert
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.update_auth_method_cert.UpdateAuthMethodCert()  # noqa: E501
        if include_optional :
            return UpdateAuthMethodCert(
                access_expires = 56, 
                bound_common_names = [
                    '0'
                    ], 
                bound_dns_sans = [
                    '0'
                    ], 
                bound_email_sans = [
                    '0'
                    ], 
                bound_extensions = [
                    '0'
                    ], 
                bound_ips = [
                    '0'
                    ], 
                bound_organizational_units = [
                    '0'
                    ], 
                bound_uri_sans = [
                    '0'
                    ], 
                certificate_data = '0', 
                force_sub_claims = True, 
                jwt_ttl = 56, 
                name = '0', 
                new_name = '0', 
                revoked_cert_ids = [
                    '0'
                    ], 
                token = '0', 
                uid_token = '0', 
                unique_identifier = '0'
            )
        else :
            return UpdateAuthMethodCert(
                name = '0',
                unique_identifier = '0',
        )

    def testUpdateAuthMethodCert(self):
        """Test UpdateAuthMethodCert"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
