# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.noti_forwarder_details_input import NotiForwarderDetailsInput  # noqa: E501
from akeyless.rest import ApiException

class TestNotiForwarderDetailsInput(unittest.TestCase):
    """NotiForwarderDetailsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NotiForwarderDetailsInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.noti_forwarder_details_input.NotiForwarderDetailsInput()  # noqa: E501
        if include_optional :
            return NotiForwarderDetailsInput(
                app_private_key_pem_base64 = '0', 
                client_secret = '0', 
                password = '0', 
                slack_noti_forwarder_details = akeyless.models.slack_noti_forwarder_details.SlackNotiForwarderDetails(
                    endpoint_url = '0', ), 
                teams_noti_forwarder_details = akeyless.models.teams_noti_forwarder_details.TeamsNotiForwarderDetails(
                    webhook_url = '0', ), 
                webhook_noti_forwarder_details = akeyless.models.webhook_noti_forwarder_details.WebhookNotiForwarderDetails(
                    certificate = '0', 
                    password = '0', 
                    private_key = '0', 
                    server_certificate = '0', 
                    token = '0', )
            )
        else :
            return NotiForwarderDetailsInput(
        )

    def testNotiForwarderDetailsInput(self):
        """Test NotiForwarderDetailsInput"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
