# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.agentic_rules import AgenticRules  # noqa: E501
from akeyless.rest import ApiException

class TestAgenticRules(unittest.TestCase):
    """AgenticRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AgenticRules
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.agentic_rules.AgenticRules()  # noqa: E501
        if include_optional :
            return AgenticRules(
                input_rules = [
                    akeyless.models.agentic_rule.AgenticRule(
                        name = '0', 
                        rule = '0', )
                    ], 
                output_rules = [
                    akeyless.models.agentic_rule.AgenticRule(
                        name = '0', 
                        rule = '0', )
                    ]
            )
        else :
            return AgenticRules(
        )

    def testAgenticRules(self):
        """Test AgenticRules"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
