# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.auth_method_update_ali_cloud import AuthMethodUpdateAliCloud  # noqa: E501
from akeyless.rest import ApiException

class TestAuthMethodUpdateAliCloud(unittest.TestCase):
    """AuthMethodUpdateAliCloud unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuthMethodUpdateAliCloud
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.auth_method_update_ali_cloud.AuthMethodUpdateAliCloud()  # noqa: E501
        if include_optional :
            return AuthMethodUpdateAliCloud(
                access_expires = 56, 
                allowed_client_type = [
                    '0'
                    ], 
                audit_logs_claims = [
                    '0'
                    ], 
                bound_account_id = [
                    '0'
                    ], 
                bound_arn = [
                    '0'
                    ], 
                bound_ips = [
                    '0'
                    ], 
                bound_resource_id = [
                    '0'
                    ], 
                bound_role_id = [
                    '0'
                    ], 
                bound_role_name = [
                    '0'
                    ], 
                bound_user_id = [
                    '0'
                    ], 
                bound_user_name = [
                    '0'
                    ], 
                delete_protection = '0', 
                description = '0', 
                expiration_event_in = [
                    '0'
                    ], 
                force_sub_claims = True, 
                gw_bound_ips = [
                    '0'
                    ], 
                json = True, 
                jwt_ttl = 56, 
                name = '0', 
                new_name = '0', 
                product_type = [
                    '0'
                    ], 
                sts_url = 'https://sts.aliyuncs.com', 
                token = '0', 
                uid_token = '0', 
                unique_identifier = '0'
            )
        else :
            return AuthMethodUpdateAliCloud(
                name = '0',
        )

    def testAuthMethodUpdateAliCloud(self):
        """Test AuthMethodUpdateAliCloud"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
