# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.target_create_linked import TargetCreateLinked  # noqa: E501
from akeyless.rest import ApiException

class TestTargetCreateLinked(unittest.TestCase):
    """TargetCreateLinked unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TargetCreateLinked
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.target_create_linked.TargetCreateLinked()  # noqa: E501
        if include_optional :
            return TargetCreateLinked(
                description = '0', 
                hosts = '0', 
                json = True, 
                name = '0', 
                parent_target_name = '0', 
                token = '0', 
                type = '0', 
                uid_token = '0'
            )
        else :
            return TargetCreateLinked(
                name = '0',
        )

    def testTargetCreateLinked(self):
        """Test TargetCreateLinked"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
