# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import akeyless
from akeyless.models.gateway_update_log_forwarding_splunk import GatewayUpdateLogForwardingSplunk  # noqa: E501
from akeyless.rest import ApiException

class TestGatewayUpdateLogForwardingSplunk(unittest.TestCase):
    """GatewayUpdateLogForwardingSplunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GatewayUpdateLogForwardingSplunk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = akeyless.models.gateway_update_log_forwarding_splunk.GatewayUpdateLogForwardingSplunk()  # noqa: E501
        if include_optional :
            return GatewayUpdateLogForwardingSplunk(
                enable = 'true', 
                enable_tls = True, 
                index = '0', 
                json = True, 
                output_format = 'text', 
                pull_interval = '10', 
                source = 'use-existing', 
                source_type = 'use-existing', 
                splunk_token = '0', 
                splunk_url = '0', 
                tls_certificate = 'use-existing', 
                token = '0', 
                uid_token = '0'
            )
        else :
            return GatewayUpdateLogForwardingSplunk(
        )

    def testGatewayUpdateLogForwardingSplunk(self):
        """Test GatewayUpdateLogForwardingSplunk"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
