# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "akeyless"
VERSION = "5.0.8"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 2.1.0", "six >= 1.10", "certifi", "python-dateutil", "psutil >= 7.0.0"]

setup(
    name=NAME,
    version=VERSION,
    description="Akeyless API",
    author="Akeyless",
    author_email="support@akeyless.io",
    url="https://www.akeyless.io/",
    keywords=["OpenAPI", "OpenAPI-Generator", "Akeyless API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    The purpose of this application is to provide access to Akeyless API.  # noqa: E501
    """
)
