# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from akeyless.configuration import Configuration


class AccountGeneralSettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'account_default_key_item_id': 'int',
        'account_default_key_name': 'str',
        'allowed_clients_ips': 'AllowedIpSettings',
        'allowed_gateways_ips': 'AllowedIpSettings',
        'auth_usage_event': 'UsageEventSetting',
        'certificate_expiration_events': 'CertificateExpirationEventsSettings',
        'data_protection_section': 'DataProtectionSection',
        'default_home_page': 'DefaultHomePage',
        'dynamic_secret_max_ttl': 'DynamicSecretMaxTtl',
        'enable_request_for_access': 'bool',
        'hide_personal_folder': 'bool',
        'hide_static_password': 'bool',
        'invalid_characters': 'str',
        'item_usage_event': 'UsageEventSetting',
        'lock_default_key': 'bool',
        'password_expiration_info': 'PasswordExpirationInfo',
        'password_policy': 'PasswordPolicyInfo',
        'password_score': 'PasswordScoreSetting',
        'protect_items_by_default': 'bool',
        'rotation_secret_max_interval': 'RotationSecretMaxInterval',
        'sharing_policy': 'SharingPolicyInfo'
    }

    attribute_map = {
        'account_default_key_item_id': 'account_default_key_item_id',
        'account_default_key_name': 'account_default_key_name',
        'allowed_clients_ips': 'allowed_clients_ips',
        'allowed_gateways_ips': 'allowed_gateways_ips',
        'auth_usage_event': 'auth_usage_event',
        'certificate_expiration_events': 'certificate_expiration_events',
        'data_protection_section': 'data_protection_section',
        'default_home_page': 'default_home_page',
        'dynamic_secret_max_ttl': 'dynamic_secret_max_ttl',
        'enable_request_for_access': 'enable_request_for_access',
        'hide_personal_folder': 'hide_personal_folder',
        'hide_static_password': 'hide_static_password',
        'invalid_characters': 'invalid_characters',
        'item_usage_event': 'item_usage_event',
        'lock_default_key': 'lock_default_key',
        'password_expiration_info': 'password_expiration_info',
        'password_policy': 'password_policy',
        'password_score': 'password_score',
        'protect_items_by_default': 'protect_items_by_default',
        'rotation_secret_max_interval': 'rotation_secret_max_interval',
        'sharing_policy': 'sharing_policy'
    }

    def __init__(self, account_default_key_item_id=None, account_default_key_name=None, allowed_clients_ips=None, allowed_gateways_ips=None, auth_usage_event=None, certificate_expiration_events=None, data_protection_section=None, default_home_page=None, dynamic_secret_max_ttl=None, enable_request_for_access=None, hide_personal_folder=None, hide_static_password=None, invalid_characters=None, item_usage_event=None, lock_default_key=None, password_expiration_info=None, password_policy=None, password_score=None, protect_items_by_default=None, rotation_secret_max_interval=None, sharing_policy=None, local_vars_configuration=None):  # noqa: E501
        """AccountGeneralSettings - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._account_default_key_item_id = None
        self._account_default_key_name = None
        self._allowed_clients_ips = None
        self._allowed_gateways_ips = None
        self._auth_usage_event = None
        self._certificate_expiration_events = None
        self._data_protection_section = None
        self._default_home_page = None
        self._dynamic_secret_max_ttl = None
        self._enable_request_for_access = None
        self._hide_personal_folder = None
        self._hide_static_password = None
        self._invalid_characters = None
        self._item_usage_event = None
        self._lock_default_key = None
        self._password_expiration_info = None
        self._password_policy = None
        self._password_score = None
        self._protect_items_by_default = None
        self._rotation_secret_max_interval = None
        self._sharing_policy = None
        self.discriminator = None

        if account_default_key_item_id is not None:
            self.account_default_key_item_id = account_default_key_item_id
        if account_default_key_name is not None:
            self.account_default_key_name = account_default_key_name
        if allowed_clients_ips is not None:
            self.allowed_clients_ips = allowed_clients_ips
        if allowed_gateways_ips is not None:
            self.allowed_gateways_ips = allowed_gateways_ips
        if auth_usage_event is not None:
            self.auth_usage_event = auth_usage_event
        if certificate_expiration_events is not None:
            self.certificate_expiration_events = certificate_expiration_events
        if data_protection_section is not None:
            self.data_protection_section = data_protection_section
        if default_home_page is not None:
            self.default_home_page = default_home_page
        if dynamic_secret_max_ttl is not None:
            self.dynamic_secret_max_ttl = dynamic_secret_max_ttl
        if enable_request_for_access is not None:
            self.enable_request_for_access = enable_request_for_access
        if hide_personal_folder is not None:
            self.hide_personal_folder = hide_personal_folder
        if hide_static_password is not None:
            self.hide_static_password = hide_static_password
        if invalid_characters is not None:
            self.invalid_characters = invalid_characters
        if item_usage_event is not None:
            self.item_usage_event = item_usage_event
        if lock_default_key is not None:
            self.lock_default_key = lock_default_key
        if password_expiration_info is not None:
            self.password_expiration_info = password_expiration_info
        if password_policy is not None:
            self.password_policy = password_policy
        if password_score is not None:
            self.password_score = password_score
        if protect_items_by_default is not None:
            self.protect_items_by_default = protect_items_by_default
        if rotation_secret_max_interval is not None:
            self.rotation_secret_max_interval = rotation_secret_max_interval
        if sharing_policy is not None:
            self.sharing_policy = sharing_policy

    @property
    def account_default_key_item_id(self):
        """Gets the account_default_key_item_id of this AccountGeneralSettings.  # noqa: E501

        AccountDefaultKeyItemID is the item ID of the DFC key item configured as the default protection key  # noqa: E501

        :return: The account_default_key_item_id of this AccountGeneralSettings.  # noqa: E501
        :rtype: int
        """
        return self._account_default_key_item_id

    @account_default_key_item_id.setter
    def account_default_key_item_id(self, account_default_key_item_id):
        """Sets the account_default_key_item_id of this AccountGeneralSettings.

        AccountDefaultKeyItemID is the item ID of the DFC key item configured as the default protection key  # noqa: E501

        :param account_default_key_item_id: The account_default_key_item_id of this AccountGeneralSettings.  # noqa: E501
        :type: int
        """

        self._account_default_key_item_id = account_default_key_item_id

    @property
    def account_default_key_name(self):
        """Gets the account_default_key_name of this AccountGeneralSettings.  # noqa: E501

        AccountDefaultKeyName is the name of the DFC key item configured as the default key This is here simply for the response to include the item name in addition to the display ID so the client can properly show this to the user. It will not be saved to the DB, only the AccountDefaultKeyItemID will.  # noqa: E501

        :return: The account_default_key_name of this AccountGeneralSettings.  # noqa: E501
        :rtype: str
        """
        return self._account_default_key_name

    @account_default_key_name.setter
    def account_default_key_name(self, account_default_key_name):
        """Sets the account_default_key_name of this AccountGeneralSettings.

        AccountDefaultKeyName is the name of the DFC key item configured as the default key This is here simply for the response to include the item name in addition to the display ID so the client can properly show this to the user. It will not be saved to the DB, only the AccountDefaultKeyItemID will.  # noqa: E501

        :param account_default_key_name: The account_default_key_name of this AccountGeneralSettings.  # noqa: E501
        :type: str
        """

        self._account_default_key_name = account_default_key_name

    @property
    def allowed_clients_ips(self):
        """Gets the allowed_clients_ips of this AccountGeneralSettings.  # noqa: E501


        :return: The allowed_clients_ips of this AccountGeneralSettings.  # noqa: E501
        :rtype: AllowedIpSettings
        """
        return self._allowed_clients_ips

    @allowed_clients_ips.setter
    def allowed_clients_ips(self, allowed_clients_ips):
        """Sets the allowed_clients_ips of this AccountGeneralSettings.


        :param allowed_clients_ips: The allowed_clients_ips of this AccountGeneralSettings.  # noqa: E501
        :type: AllowedIpSettings
        """

        self._allowed_clients_ips = allowed_clients_ips

    @property
    def allowed_gateways_ips(self):
        """Gets the allowed_gateways_ips of this AccountGeneralSettings.  # noqa: E501


        :return: The allowed_gateways_ips of this AccountGeneralSettings.  # noqa: E501
        :rtype: AllowedIpSettings
        """
        return self._allowed_gateways_ips

    @allowed_gateways_ips.setter
    def allowed_gateways_ips(self, allowed_gateways_ips):
        """Sets the allowed_gateways_ips of this AccountGeneralSettings.


        :param allowed_gateways_ips: The allowed_gateways_ips of this AccountGeneralSettings.  # noqa: E501
        :type: AllowedIpSettings
        """

        self._allowed_gateways_ips = allowed_gateways_ips

    @property
    def auth_usage_event(self):
        """Gets the auth_usage_event of this AccountGeneralSettings.  # noqa: E501


        :return: The auth_usage_event of this AccountGeneralSettings.  # noqa: E501
        :rtype: UsageEventSetting
        """
        return self._auth_usage_event

    @auth_usage_event.setter
    def auth_usage_event(self, auth_usage_event):
        """Sets the auth_usage_event of this AccountGeneralSettings.


        :param auth_usage_event: The auth_usage_event of this AccountGeneralSettings.  # noqa: E501
        :type: UsageEventSetting
        """

        self._auth_usage_event = auth_usage_event

    @property
    def certificate_expiration_events(self):
        """Gets the certificate_expiration_events of this AccountGeneralSettings.  # noqa: E501


        :return: The certificate_expiration_events of this AccountGeneralSettings.  # noqa: E501
        :rtype: CertificateExpirationEventsSettings
        """
        return self._certificate_expiration_events

    @certificate_expiration_events.setter
    def certificate_expiration_events(self, certificate_expiration_events):
        """Sets the certificate_expiration_events of this AccountGeneralSettings.


        :param certificate_expiration_events: The certificate_expiration_events of this AccountGeneralSettings.  # noqa: E501
        :type: CertificateExpirationEventsSettings
        """

        self._certificate_expiration_events = certificate_expiration_events

    @property
    def data_protection_section(self):
        """Gets the data_protection_section of this AccountGeneralSettings.  # noqa: E501


        :return: The data_protection_section of this AccountGeneralSettings.  # noqa: E501
        :rtype: DataProtectionSection
        """
        return self._data_protection_section

    @data_protection_section.setter
    def data_protection_section(self, data_protection_section):
        """Sets the data_protection_section of this AccountGeneralSettings.


        :param data_protection_section: The data_protection_section of this AccountGeneralSettings.  # noqa: E501
        :type: DataProtectionSection
        """

        self._data_protection_section = data_protection_section

    @property
    def default_home_page(self):
        """Gets the default_home_page of this AccountGeneralSettings.  # noqa: E501


        :return: The default_home_page of this AccountGeneralSettings.  # noqa: E501
        :rtype: DefaultHomePage
        """
        return self._default_home_page

    @default_home_page.setter
    def default_home_page(self, default_home_page):
        """Sets the default_home_page of this AccountGeneralSettings.


        :param default_home_page: The default_home_page of this AccountGeneralSettings.  # noqa: E501
        :type: DefaultHomePage
        """

        self._default_home_page = default_home_page

    @property
    def dynamic_secret_max_ttl(self):
        """Gets the dynamic_secret_max_ttl of this AccountGeneralSettings.  # noqa: E501


        :return: The dynamic_secret_max_ttl of this AccountGeneralSettings.  # noqa: E501
        :rtype: DynamicSecretMaxTtl
        """
        return self._dynamic_secret_max_ttl

    @dynamic_secret_max_ttl.setter
    def dynamic_secret_max_ttl(self, dynamic_secret_max_ttl):
        """Sets the dynamic_secret_max_ttl of this AccountGeneralSettings.


        :param dynamic_secret_max_ttl: The dynamic_secret_max_ttl of this AccountGeneralSettings.  # noqa: E501
        :type: DynamicSecretMaxTtl
        """

        self._dynamic_secret_max_ttl = dynamic_secret_max_ttl

    @property
    def enable_request_for_access(self):
        """Gets the enable_request_for_access of this AccountGeneralSettings.  # noqa: E501


        :return: The enable_request_for_access of this AccountGeneralSettings.  # noqa: E501
        :rtype: bool
        """
        return self._enable_request_for_access

    @enable_request_for_access.setter
    def enable_request_for_access(self, enable_request_for_access):
        """Sets the enable_request_for_access of this AccountGeneralSettings.


        :param enable_request_for_access: The enable_request_for_access of this AccountGeneralSettings.  # noqa: E501
        :type: bool
        """

        self._enable_request_for_access = enable_request_for_access

    @property
    def hide_personal_folder(self):
        """Gets the hide_personal_folder of this AccountGeneralSettings.  # noqa: E501


        :return: The hide_personal_folder of this AccountGeneralSettings.  # noqa: E501
        :rtype: bool
        """
        return self._hide_personal_folder

    @hide_personal_folder.setter
    def hide_personal_folder(self, hide_personal_folder):
        """Sets the hide_personal_folder of this AccountGeneralSettings.


        :param hide_personal_folder: The hide_personal_folder of this AccountGeneralSettings.  # noqa: E501
        :type: bool
        """

        self._hide_personal_folder = hide_personal_folder

    @property
    def hide_static_password(self):
        """Gets the hide_static_password of this AccountGeneralSettings.  # noqa: E501


        :return: The hide_static_password of this AccountGeneralSettings.  # noqa: E501
        :rtype: bool
        """
        return self._hide_static_password

    @hide_static_password.setter
    def hide_static_password(self, hide_static_password):
        """Sets the hide_static_password of this AccountGeneralSettings.


        :param hide_static_password: The hide_static_password of this AccountGeneralSettings.  # noqa: E501
        :type: bool
        """

        self._hide_static_password = hide_static_password

    @property
    def invalid_characters(self):
        """Gets the invalid_characters of this AccountGeneralSettings.  # noqa: E501

        InvalidCharacters is the invalid characters for items/targets/roles/auths/notifier_forwarder naming convention  # noqa: E501

        :return: The invalid_characters of this AccountGeneralSettings.  # noqa: E501
        :rtype: str
        """
        return self._invalid_characters

    @invalid_characters.setter
    def invalid_characters(self, invalid_characters):
        """Sets the invalid_characters of this AccountGeneralSettings.

        InvalidCharacters is the invalid characters for items/targets/roles/auths/notifier_forwarder naming convention  # noqa: E501

        :param invalid_characters: The invalid_characters of this AccountGeneralSettings.  # noqa: E501
        :type: str
        """

        self._invalid_characters = invalid_characters

    @property
    def item_usage_event(self):
        """Gets the item_usage_event of this AccountGeneralSettings.  # noqa: E501


        :return: The item_usage_event of this AccountGeneralSettings.  # noqa: E501
        :rtype: UsageEventSetting
        """
        return self._item_usage_event

    @item_usage_event.setter
    def item_usage_event(self, item_usage_event):
        """Sets the item_usage_event of this AccountGeneralSettings.


        :param item_usage_event: The item_usage_event of this AccountGeneralSettings.  # noqa: E501
        :type: UsageEventSetting
        """

        self._item_usage_event = item_usage_event

    @property
    def lock_default_key(self):
        """Gets the lock_default_key of this AccountGeneralSettings.  # noqa: E501

        LockDefaultKey determines whether the configured default key can be updated by end-users on a per-request basis true - all requests use the configured default key false - every request can determine its protection key (default) nil - change nothing (every request can determine its protection key (default)) This parameter is only relevant if AccountDefaultKeyItemID is not empty  # noqa: E501

        :return: The lock_default_key of this AccountGeneralSettings.  # noqa: E501
        :rtype: bool
        """
        return self._lock_default_key

    @lock_default_key.setter
    def lock_default_key(self, lock_default_key):
        """Sets the lock_default_key of this AccountGeneralSettings.

        LockDefaultKey determines whether the configured default key can be updated by end-users on a per-request basis true - all requests use the configured default key false - every request can determine its protection key (default) nil - change nothing (every request can determine its protection key (default)) This parameter is only relevant if AccountDefaultKeyItemID is not empty  # noqa: E501

        :param lock_default_key: The lock_default_key of this AccountGeneralSettings.  # noqa: E501
        :type: bool
        """

        self._lock_default_key = lock_default_key

    @property
    def password_expiration_info(self):
        """Gets the password_expiration_info of this AccountGeneralSettings.  # noqa: E501


        :return: The password_expiration_info of this AccountGeneralSettings.  # noqa: E501
        :rtype: PasswordExpirationInfo
        """
        return self._password_expiration_info

    @password_expiration_info.setter
    def password_expiration_info(self, password_expiration_info):
        """Sets the password_expiration_info of this AccountGeneralSettings.


        :param password_expiration_info: The password_expiration_info of this AccountGeneralSettings.  # noqa: E501
        :type: PasswordExpirationInfo
        """

        self._password_expiration_info = password_expiration_info

    @property
    def password_policy(self):
        """Gets the password_policy of this AccountGeneralSettings.  # noqa: E501


        :return: The password_policy of this AccountGeneralSettings.  # noqa: E501
        :rtype: PasswordPolicyInfo
        """
        return self._password_policy

    @password_policy.setter
    def password_policy(self, password_policy):
        """Sets the password_policy of this AccountGeneralSettings.


        :param password_policy: The password_policy of this AccountGeneralSettings.  # noqa: E501
        :type: PasswordPolicyInfo
        """

        self._password_policy = password_policy

    @property
    def password_score(self):
        """Gets the password_score of this AccountGeneralSettings.  # noqa: E501


        :return: The password_score of this AccountGeneralSettings.  # noqa: E501
        :rtype: PasswordScoreSetting
        """
        return self._password_score

    @password_score.setter
    def password_score(self, password_score):
        """Sets the password_score of this AccountGeneralSettings.


        :param password_score: The password_score of this AccountGeneralSettings.  # noqa: E501
        :type: PasswordScoreSetting
        """

        self._password_score = password_score

    @property
    def protect_items_by_default(self):
        """Gets the protect_items_by_default of this AccountGeneralSettings.  # noqa: E501


        :return: The protect_items_by_default of this AccountGeneralSettings.  # noqa: E501
        :rtype: bool
        """
        return self._protect_items_by_default

    @protect_items_by_default.setter
    def protect_items_by_default(self, protect_items_by_default):
        """Sets the protect_items_by_default of this AccountGeneralSettings.


        :param protect_items_by_default: The protect_items_by_default of this AccountGeneralSettings.  # noqa: E501
        :type: bool
        """

        self._protect_items_by_default = protect_items_by_default

    @property
    def rotation_secret_max_interval(self):
        """Gets the rotation_secret_max_interval of this AccountGeneralSettings.  # noqa: E501


        :return: The rotation_secret_max_interval of this AccountGeneralSettings.  # noqa: E501
        :rtype: RotationSecretMaxInterval
        """
        return self._rotation_secret_max_interval

    @rotation_secret_max_interval.setter
    def rotation_secret_max_interval(self, rotation_secret_max_interval):
        """Sets the rotation_secret_max_interval of this AccountGeneralSettings.


        :param rotation_secret_max_interval: The rotation_secret_max_interval of this AccountGeneralSettings.  # noqa: E501
        :type: RotationSecretMaxInterval
        """

        self._rotation_secret_max_interval = rotation_secret_max_interval

    @property
    def sharing_policy(self):
        """Gets the sharing_policy of this AccountGeneralSettings.  # noqa: E501


        :return: The sharing_policy of this AccountGeneralSettings.  # noqa: E501
        :rtype: SharingPolicyInfo
        """
        return self._sharing_policy

    @sharing_policy.setter
    def sharing_policy(self, sharing_policy):
        """Sets the sharing_policy of this AccountGeneralSettings.


        :param sharing_policy: The sharing_policy of this AccountGeneralSettings.  # noqa: E501
        :type: SharingPolicyInfo
        """

        self._sharing_policy = sharing_policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountGeneralSettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AccountGeneralSettings):
            return True

        return self.to_dict() != other.to_dict()
