# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from akeyless.configuration import Configuration


class AccountCustomFieldCreate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'json': 'bool',
        'name': 'str',
        'object': 'str',
        'object_type': 'str',
        'required': 'bool',
        'token': 'str',
        'uid_token': 'str'
    }

    attribute_map = {
        'json': 'json',
        'name': 'name',
        'object': 'object',
        'object_type': 'object-type',
        'required': 'required',
        'token': 'token',
        'uid_token': 'uid-token'
    }

    def __init__(self, json=False, name=None, object='ITEM', object_type=None, required=False, token=None, uid_token=None, local_vars_configuration=None):  # noqa: E501
        """AccountCustomFieldCreate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._json = None
        self._name = None
        self._object = None
        self._object_type = None
        self._required = None
        self._token = None
        self._uid_token = None
        self.discriminator = None

        if json is not None:
            self.json = json
        self.name = name
        self.object = object
        self.object_type = object_type
        if required is not None:
            self.required = required
        if token is not None:
            self.token = token
        if uid_token is not None:
            self.uid_token = uid_token

    @property
    def json(self):
        """Gets the json of this AccountCustomFieldCreate.  # noqa: E501

        Set output format to JSON  # noqa: E501

        :return: The json of this AccountCustomFieldCreate.  # noqa: E501
        :rtype: bool
        """
        return self._json

    @json.setter
    def json(self, json):
        """Sets the json of this AccountCustomFieldCreate.

        Set output format to JSON  # noqa: E501

        :param json: The json of this AccountCustomFieldCreate.  # noqa: E501
        :type: bool
        """

        self._json = json

    @property
    def name(self):
        """Gets the name of this AccountCustomFieldCreate.  # noqa: E501

        The name of the custom field  # noqa: E501

        :return: The name of this AccountCustomFieldCreate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AccountCustomFieldCreate.

        The name of the custom field  # noqa: E501

        :param name: The name of this AccountCustomFieldCreate.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def object(self):
        """Gets the object of this AccountCustomFieldCreate.  # noqa: E501

        The object to create the custom field  # noqa: E501

        :return: The object of this AccountCustomFieldCreate.  # noqa: E501
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this AccountCustomFieldCreate.

        The object to create the custom field  # noqa: E501

        :param object: The object of this AccountCustomFieldCreate.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and object is None:  # noqa: E501
            raise ValueError("Invalid value for `object`, must not be `None`")  # noqa: E501

        self._object = object

    @property
    def object_type(self):
        """Gets the object_type of this AccountCustomFieldCreate.  # noqa: E501

        The object type to create the custom field [e.g. STATIC_SECRET,DYNAMIC_SECRET,ROTATED_SECRET]  # noqa: E501

        :return: The object_type of this AccountCustomFieldCreate.  # noqa: E501
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """Sets the object_type of this AccountCustomFieldCreate.

        The object type to create the custom field [e.g. STATIC_SECRET,DYNAMIC_SECRET,ROTATED_SECRET]  # noqa: E501

        :param object_type: The object_type of this AccountCustomFieldCreate.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and object_type is None:  # noqa: E501
            raise ValueError("Invalid value for `object_type`, must not be `None`")  # noqa: E501

        self._object_type = object_type

    @property
    def required(self):
        """Gets the required of this AccountCustomFieldCreate.  # noqa: E501

        Specify whether the custom field is mandatory  # noqa: E501

        :return: The required of this AccountCustomFieldCreate.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this AccountCustomFieldCreate.

        Specify whether the custom field is mandatory  # noqa: E501

        :param required: The required of this AccountCustomFieldCreate.  # noqa: E501
        :type: bool
        """

        self._required = required

    @property
    def token(self):
        """Gets the token of this AccountCustomFieldCreate.  # noqa: E501

        Authentication token (see `/auth` and `/configure`)  # noqa: E501

        :return: The token of this AccountCustomFieldCreate.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this AccountCustomFieldCreate.

        Authentication token (see `/auth` and `/configure`)  # noqa: E501

        :param token: The token of this AccountCustomFieldCreate.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def uid_token(self):
        """Gets the uid_token of this AccountCustomFieldCreate.  # noqa: E501

        The universal identity token, Required only for universal_identity authentication  # noqa: E501

        :return: The uid_token of this AccountCustomFieldCreate.  # noqa: E501
        :rtype: str
        """
        return self._uid_token

    @uid_token.setter
    def uid_token(self, uid_token):
        """Sets the uid_token of this AccountCustomFieldCreate.

        The universal identity token, Required only for universal_identity authentication  # noqa: E501

        :param uid_token: The uid_token of this AccountCustomFieldCreate.  # noqa: E501
        :type: str
        """

        self._uid_token = uid_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountCustomFieldCreate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AccountCustomFieldCreate):
            return True

        return self.to_dict() != other.to_dict()
