# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from akeyless.configuration import Configuration


class CreateLinkedTarget(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'hosts': 'str',
        'json': 'bool',
        'name': 'str',
        'parent_target_name': 'str',
        'token': 'str',
        'type': 'str',
        'uid_token': 'str'
    }

    attribute_map = {
        'description': 'description',
        'hosts': 'hosts',
        'json': 'json',
        'name': 'name',
        'parent_target_name': 'parent-target-name',
        'token': 'token',
        'type': 'type',
        'uid_token': 'uid-token'
    }

    def __init__(self, description=None, hosts=None, json=False, name=None, parent_target_name=None, token=None, type=None, uid_token=None, local_vars_configuration=None):  # noqa: E501
        """CreateLinkedTarget - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._hosts = None
        self._json = None
        self._name = None
        self._parent_target_name = None
        self._token = None
        self._type = None
        self._uid_token = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if hosts is not None:
            self.hosts = hosts
        if json is not None:
            self.json = json
        self.name = name
        if parent_target_name is not None:
            self.parent_target_name = parent_target_name
        if token is not None:
            self.token = token
        if type is not None:
            self.type = type
        if uid_token is not None:
            self.uid_token = uid_token

    @property
    def description(self):
        """Gets the description of this CreateLinkedTarget.  # noqa: E501

        Description of the object  # noqa: E501

        :return: The description of this CreateLinkedTarget.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateLinkedTarget.

        Description of the object  # noqa: E501

        :param description: The description of this CreateLinkedTarget.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def hosts(self):
        """Gets the hosts of this CreateLinkedTarget.  # noqa: E501

        A comma seperated list of server hosts and server descriptions joined by semicolon ';' (i.e. 'server-dev.com;My Dev server,server-prod.com;My Prod server description')  # noqa: E501

        :return: The hosts of this CreateLinkedTarget.  # noqa: E501
        :rtype: str
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this CreateLinkedTarget.

        A comma seperated list of server hosts and server descriptions joined by semicolon ';' (i.e. 'server-dev.com;My Dev server,server-prod.com;My Prod server description')  # noqa: E501

        :param hosts: The hosts of this CreateLinkedTarget.  # noqa: E501
        :type: str
        """

        self._hosts = hosts

    @property
    def json(self):
        """Gets the json of this CreateLinkedTarget.  # noqa: E501

        Set output format to JSON  # noqa: E501

        :return: The json of this CreateLinkedTarget.  # noqa: E501
        :rtype: bool
        """
        return self._json

    @json.setter
    def json(self, json):
        """Sets the json of this CreateLinkedTarget.

        Set output format to JSON  # noqa: E501

        :param json: The json of this CreateLinkedTarget.  # noqa: E501
        :type: bool
        """

        self._json = json

    @property
    def name(self):
        """Gets the name of this CreateLinkedTarget.  # noqa: E501

        Target name  # noqa: E501

        :return: The name of this CreateLinkedTarget.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateLinkedTarget.

        Target name  # noqa: E501

        :param name: The name of this CreateLinkedTarget.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def parent_target_name(self):
        """Gets the parent_target_name of this CreateLinkedTarget.  # noqa: E501

        The parent Target name  # noqa: E501

        :return: The parent_target_name of this CreateLinkedTarget.  # noqa: E501
        :rtype: str
        """
        return self._parent_target_name

    @parent_target_name.setter
    def parent_target_name(self, parent_target_name):
        """Sets the parent_target_name of this CreateLinkedTarget.

        The parent Target name  # noqa: E501

        :param parent_target_name: The parent_target_name of this CreateLinkedTarget.  # noqa: E501
        :type: str
        """

        self._parent_target_name = parent_target_name

    @property
    def token(self):
        """Gets the token of this CreateLinkedTarget.  # noqa: E501

        Authentication token (see `/auth` and `/configure`)  # noqa: E501

        :return: The token of this CreateLinkedTarget.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this CreateLinkedTarget.

        Authentication token (see `/auth` and `/configure`)  # noqa: E501

        :param token: The token of this CreateLinkedTarget.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def type(self):
        """Gets the type of this CreateLinkedTarget.  # noqa: E501

        Specifies the hosts type, relevant only when working without parent target  # noqa: E501

        :return: The type of this CreateLinkedTarget.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CreateLinkedTarget.

        Specifies the hosts type, relevant only when working without parent target  # noqa: E501

        :param type: The type of this CreateLinkedTarget.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def uid_token(self):
        """Gets the uid_token of this CreateLinkedTarget.  # noqa: E501

        The universal identity token, Required only for universal_identity authentication  # noqa: E501

        :return: The uid_token of this CreateLinkedTarget.  # noqa: E501
        :rtype: str
        """
        return self._uid_token

    @uid_token.setter
    def uid_token(self, uid_token):
        """Sets the uid_token of this CreateLinkedTarget.

        The universal identity token, Required only for universal_identity authentication  # noqa: E501

        :param uid_token: The uid_token of this CreateLinkedTarget.  # noqa: E501
        :type: str
        """

        self._uid_token = uid_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateLinkedTarget):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateLinkedTarget):
            return True

        return self.to_dict() != other.to_dict()
