# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from akeyless.configuration import Configuration


class EmailCustomizationAccountInformationValues(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'account_id': 'str',
        'alias_name': 'str',
        'company_name': 'str',
        'tenant_name': 'str'
    }

    attribute_map = {
        'account_id': 'account_id',
        'alias_name': 'alias_name',
        'company_name': 'company_name',
        'tenant_name': 'tenant_name'
    }

    def __init__(self, account_id=None, alias_name=None, company_name=None, tenant_name=None, local_vars_configuration=None):  # noqa: E501
        """EmailCustomizationAccountInformationValues - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._account_id = None
        self._alias_name = None
        self._company_name = None
        self._tenant_name = None
        self.discriminator = None

        if account_id is not None:
            self.account_id = account_id
        if alias_name is not None:
            self.alias_name = alias_name
        if company_name is not None:
            self.company_name = company_name
        if tenant_name is not None:
            self.tenant_name = tenant_name

    @property
    def account_id(self):
        """Gets the account_id of this EmailCustomizationAccountInformationValues.  # noqa: E501


        :return: The account_id of this EmailCustomizationAccountInformationValues.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this EmailCustomizationAccountInformationValues.


        :param account_id: The account_id of this EmailCustomizationAccountInformationValues.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def alias_name(self):
        """Gets the alias_name of this EmailCustomizationAccountInformationValues.  # noqa: E501


        :return: The alias_name of this EmailCustomizationAccountInformationValues.  # noqa: E501
        :rtype: str
        """
        return self._alias_name

    @alias_name.setter
    def alias_name(self, alias_name):
        """Sets the alias_name of this EmailCustomizationAccountInformationValues.


        :param alias_name: The alias_name of this EmailCustomizationAccountInformationValues.  # noqa: E501
        :type: str
        """

        self._alias_name = alias_name

    @property
    def company_name(self):
        """Gets the company_name of this EmailCustomizationAccountInformationValues.  # noqa: E501


        :return: The company_name of this EmailCustomizationAccountInformationValues.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this EmailCustomizationAccountInformationValues.


        :param company_name: The company_name of this EmailCustomizationAccountInformationValues.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def tenant_name(self):
        """Gets the tenant_name of this EmailCustomizationAccountInformationValues.  # noqa: E501


        :return: The tenant_name of this EmailCustomizationAccountInformationValues.  # noqa: E501
        :rtype: str
        """
        return self._tenant_name

    @tenant_name.setter
    def tenant_name(self, tenant_name):
        """Sets the tenant_name of this EmailCustomizationAccountInformationValues.


        :param tenant_name: The tenant_name of this EmailCustomizationAccountInformationValues.  # noqa: E501
        :type: str
        """

        self._tenant_name = tenant_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailCustomizationAccountInformationValues):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EmailCustomizationAccountInformationValues):
            return True

        return self.to_dict() != other.to_dict()
