# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from akeyless.configuration import Configuration


class ResponseStopShareItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'errors': 'list[EmailError]',
        'item_name': 'str'
    }

    attribute_map = {
        'errors': 'errors',
        'item_name': 'item_name'
    }

    def __init__(self, errors=None, item_name=None, local_vars_configuration=None):  # noqa: E501
        """ResponseStopShareItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._errors = None
        self._item_name = None
        self.discriminator = None

        if errors is not None:
            self.errors = errors
        if item_name is not None:
            self.item_name = item_name

    @property
    def errors(self):
        """Gets the errors of this ResponseStopShareItem.  # noqa: E501


        :return: The errors of this ResponseStopShareItem.  # noqa: E501
        :rtype: list[EmailError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this ResponseStopShareItem.


        :param errors: The errors of this ResponseStopShareItem.  # noqa: E501
        :type: list[EmailError]
        """

        self._errors = errors

    @property
    def item_name(self):
        """Gets the item_name of this ResponseStopShareItem.  # noqa: E501


        :return: The item_name of this ResponseStopShareItem.  # noqa: E501
        :rtype: str
        """
        return self._item_name

    @item_name.setter
    def item_name(self, item_name):
        """Sets the item_name of this ResponseStopShareItem.


        :param item_name: The item_name of this ResponseStopShareItem.  # noqa: E501
        :type: str
        """

        self._item_name = item_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseStopShareItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResponseStopShareItem):
            return True

        return self.to_dict() != other.to_dict()
