# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from akeyless.configuration import Configuration


class RotateKeyOutput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'new_item_version': 'int',
        'next_rotation_date': 'datetime'
    }

    attribute_map = {
        'new_item_version': 'new_item_version',
        'next_rotation_date': 'next_rotation_date'
    }

    def __init__(self, new_item_version=None, next_rotation_date=None, local_vars_configuration=None):  # noqa: E501
        """RotateKeyOutput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._new_item_version = None
        self._next_rotation_date = None
        self.discriminator = None

        if new_item_version is not None:
            self.new_item_version = new_item_version
        if next_rotation_date is not None:
            self.next_rotation_date = next_rotation_date

    @property
    def new_item_version(self):
        """Gets the new_item_version of this RotateKeyOutput.  # noqa: E501


        :return: The new_item_version of this RotateKeyOutput.  # noqa: E501
        :rtype: int
        """
        return self._new_item_version

    @new_item_version.setter
    def new_item_version(self, new_item_version):
        """Sets the new_item_version of this RotateKeyOutput.


        :param new_item_version: The new_item_version of this RotateKeyOutput.  # noqa: E501
        :type: int
        """

        self._new_item_version = new_item_version

    @property
    def next_rotation_date(self):
        """Gets the next_rotation_date of this RotateKeyOutput.  # noqa: E501


        :return: The next_rotation_date of this RotateKeyOutput.  # noqa: E501
        :rtype: datetime
        """
        return self._next_rotation_date

    @next_rotation_date.setter
    def next_rotation_date(self, next_rotation_date):
        """Sets the next_rotation_date of this RotateKeyOutput.


        :param next_rotation_date: The next_rotation_date of this RotateKeyOutput.  # noqa: E501
        :type: datetime
        """

        self._next_rotation_date = next_rotation_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RotateKeyOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RotateKeyOutput):
            return True

        return self.to_dict() != other.to_dict()
