# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from akeyless.configuration import Configuration


class TargetNameWithHosts(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hosts': 'list[str]',
        'target_name': 'str'
    }

    attribute_map = {
        'hosts': 'hosts',
        'target_name': 'target_name'
    }

    def __init__(self, hosts=None, target_name=None, local_vars_configuration=None):  # noqa: E501
        """TargetNameWithHosts - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._hosts = None
        self._target_name = None
        self.discriminator = None

        if hosts is not None:
            self.hosts = hosts
        if target_name is not None:
            self.target_name = target_name

    @property
    def hosts(self):
        """Gets the hosts of this TargetNameWithHosts.  # noqa: E501


        :return: The hosts of this TargetNameWithHosts.  # noqa: E501
        :rtype: list[str]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this TargetNameWithHosts.


        :param hosts: The hosts of this TargetNameWithHosts.  # noqa: E501
        :type: list[str]
        """

        self._hosts = hosts

    @property
    def target_name(self):
        """Gets the target_name of this TargetNameWithHosts.  # noqa: E501


        :return: The target_name of this TargetNameWithHosts.  # noqa: E501
        :rtype: str
        """
        return self._target_name

    @target_name.setter
    def target_name(self, target_name):
        """Sets the target_name of this TargetNameWithHosts.


        :param target_name: The target_name of this TargetNameWithHosts.  # noqa: E501
        :type: str
        """

        self._target_name = target_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TargetNameWithHosts):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TargetNameWithHosts):
            return True

        return self.to_dict() != other.to_dict()
