# coding: utf-8

"""
    Akeyless API

    The purpose of this application is to provide access to Akeyless API.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: support@akeyless.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from akeyless.configuration import Configuration


class WebhookNotiForwarderDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'certificate': 'str',
        'password': 'str',
        'private_key': 'str',
        'server_certificate': 'str',
        'token': 'str'
    }

    attribute_map = {
        'certificate': 'certificate',
        'password': 'password',
        'private_key': 'private_key',
        'server_certificate': 'server_certificate',
        'token': 'token'
    }

    def __init__(self, certificate=None, password=None, private_key=None, server_certificate=None, token=None, local_vars_configuration=None):  # noqa: E501
        """WebhookNotiForwarderDetails - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._certificate = None
        self._password = None
        self._private_key = None
        self._server_certificate = None
        self._token = None
        self.discriminator = None

        if certificate is not None:
            self.certificate = certificate
        if password is not None:
            self.password = password
        if private_key is not None:
            self.private_key = private_key
        if server_certificate is not None:
            self.server_certificate = server_certificate
        if token is not None:
            self.token = token

    @property
    def certificate(self):
        """Gets the certificate of this WebhookNotiForwarderDetails.  # noqa: E501

        Auth type - Certificate  # noqa: E501

        :return: The certificate of this WebhookNotiForwarderDetails.  # noqa: E501
        :rtype: str
        """
        return self._certificate

    @certificate.setter
    def certificate(self, certificate):
        """Sets the certificate of this WebhookNotiForwarderDetails.

        Auth type - Certificate  # noqa: E501

        :param certificate: The certificate of this WebhookNotiForwarderDetails.  # noqa: E501
        :type: str
        """

        self._certificate = certificate

    @property
    def password(self):
        """Gets the password of this WebhookNotiForwarderDetails.  # noqa: E501

        Auth type - User Password  # noqa: E501

        :return: The password of this WebhookNotiForwarderDetails.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this WebhookNotiForwarderDetails.

        Auth type - User Password  # noqa: E501

        :param password: The password of this WebhookNotiForwarderDetails.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def private_key(self):
        """Gets the private_key of this WebhookNotiForwarderDetails.  # noqa: E501


        :return: The private_key of this WebhookNotiForwarderDetails.  # noqa: E501
        :rtype: str
        """
        return self._private_key

    @private_key.setter
    def private_key(self, private_key):
        """Sets the private_key of this WebhookNotiForwarderDetails.


        :param private_key: The private_key of this WebhookNotiForwarderDetails.  # noqa: E501
        :type: str
        """

        self._private_key = private_key

    @property
    def server_certificate(self):
        """Gets the server_certificate of this WebhookNotiForwarderDetails.  # noqa: E501


        :return: The server_certificate of this WebhookNotiForwarderDetails.  # noqa: E501
        :rtype: str
        """
        return self._server_certificate

    @server_certificate.setter
    def server_certificate(self, server_certificate):
        """Sets the server_certificate of this WebhookNotiForwarderDetails.


        :param server_certificate: The server_certificate of this WebhookNotiForwarderDetails.  # noqa: E501
        :type: str
        """

        self._server_certificate = server_certificate

    @property
    def token(self):
        """Gets the token of this WebhookNotiForwarderDetails.  # noqa: E501

        Auth type - Token  # noqa: E501

        :return: The token of this WebhookNotiForwarderDetails.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this WebhookNotiForwarderDetails.

        Auth type - Token  # noqa: E501

        :param token: The token of this WebhookNotiForwarderDetails.  # noqa: E501
        :type: str
        """

        self._token = token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebhookNotiForwarderDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WebhookNotiForwarderDetails):
            return True

        return self.to_dict() != other.to_dict()
